#!/usr/bin/env bash
#export PATH="/opt/wine-osu/bin:$PATH" #custom WINE ArchLinux
export PATH="$HOME/wine-osu/bin:$PATH" #custom WINE new

export WINEARCH=win32
export WINEPREFIX="$HOME/.wineosu"
export WINEFSYNC=1

export STAGING_AUDIO_DURATION=13333 #1.333ms at 48KHz
export STAGING_AUDIO_PERIOD=13333 #1.333ms at 48KHz

#export vblank_mode=0 #For AMD, Intel and others
export __GL_SYNC_TO_VBLANK=0 #For NVIDIA 

cd ~/osu
#wine --version
wine "osu!.exe" #-devserver gatari.pw
