#!/bin/bash

# Script Menu with local script execution
# Author: Generated by valera456 AI gcc arch linux lazer tachyon peppy
# Version: 1.1

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to display header
show_header() {
    clear
    echo -e "${BLUE}"
    echo "=========================================="
    echo "    9 EBU 4TO DELAETS9, EBANINA PLOTNA9"
    echo "=========================================="
    echo -e "${NC}"
}

# Function to run a local script
run_local_script() {
    local script_name="$1"
    # Get the directory where this menu.sh script is located
    local script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    local script_path="$script_dir/$script_name"
    
    if [ ! -f "$script_path" ]; then
        print_error "Script '$script_name' not found in script directory!"
        print_warning "Please make sure the script exists in the same folder as this menu."
        print_status "Script directory: $script_dir"
        print_status "Current directory: $(pwd)"
        print_status "Looking for: $script_path"
        print_status "Contents of current directory:"
        ls -la
        return 1
    fi
    
    if [ ! -x "$script_path" ]; then
        print_status "Making script executable..."
        chmod +x "$script_path"
    fi
    
    print_status "Running $script_name with elevated privileges..."
    echo "------------------------------------------"
    
    # Execute the script with sudo
    sudo "$script_path"
    
    local exit_code=$?
    echo "------------------------------------------"
    
    if [ $exit_code -eq 0 ]; then
        print_success "Script executed successfully!"
    else
        print_error "Script exited with error code: $exit_code"
    fi
    
    return $exit_code
}

# Function to show main menu. ADD NEW SCRIPTS HERE.
show_menu() {
    echo -e "${BLUE}Available Scripts:${NC}"
    echo -e "${GREEN}1.${NC} Install i3 desktop"
    echo -e "${GREEN}2.${NC} Install Openbox desktop"
    echo -e "${GREEN}3.${NC} Install wine + osu!stable"
    echo -e "${GREEN}4.${NC} Install osu!lazer"
    echo -e "${GREEN}5.${NC} Install Pipewire configs"
    echo -e "${GREEN}6.${NC} Install OpenTabletDriver configs"
    echo -e "${GREEN}7.${NC} Install Wooting configs"
    echo -e "${GREEN}8.${NC} Exit"
    echo -e "${BLUE}==========================================${NC}"
}

# Main program loop. ADD NEW SCRIPTS HERE.
while true; do
    show_header
    show_menu
    
    read -p "Choose an option [1-8]: " choice
    echo
    
    case $choice in
        1)
            run_local_script "i3.sh"
            ;;
        2)
            run_local_script "openbox.sh"
            ;;
        3)
            run_local_script "stable.sh"
            ;;
        4)
            run_local_script "lazer.sh"
            ;;
        5)
            run_local_script "pipewire.sh"
            ;;
        6)
            run_local_script "otd.sh"
            ;;
        7)
            run_local_script "wooting.sh"
            ;;
        8)
            exit 0
            ;;
        *)
            print_error "Invalid option! Please choose between 1-8."
            ;;
    esac
    
    echo
    read -p "Press Enter to continue..."
done